name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust to your default branch or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate API Key File
      run: echo "API_KEY2 = '${{ secrets.API_KEY }}';" > api_key.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Adjust to the directory where your built files are located